# Generated by Django 2.0.1 on 2018-01-24 14:16

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbatim_family_id', models.IntegerField(help_text='Verbatim ID, from the Access database', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('vernacular_name', models.CharField(blank=True, max_length=255)),
                ('vernacular_name_de', models.CharField(blank=True, max_length=255, null=True)),
                ('vernacular_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('vernacular_name_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('vernacular_name_nl', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'families',
            },
        ),
        migrations.CreateModel(
            name='PageFragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.SlugField(unique=True)),
                ('content_nl', markdownx.models.MarkdownxField(blank=True)),
                ('content_en', markdownx.models.MarkdownxField(blank=True)),
                ('content_fr', markdownx.models.MarkdownxField(blank=True)),
                ('content_de', markdownx.models.MarkdownxField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('order', models.IntegerField(help_text='In presence tables: order in which the provinces are displayed', unique=True)),
                ('historical', models.BooleanField(help_text="The province doesn't exists anymore")),
                ('recent', models.BooleanField(help_text='The province was created at province split')),
                ('polygon_reference', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesPresence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbatim_status_id', models.IntegerField(help_text='Verbatim ID, from the Access database', unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'statuses',
            },
        ),
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='speciespresence',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lepidoptera.TimePeriod'),
        ),
        migrations.AddField(
            model_name='speciespresence',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lepidoptera.Province'),
        ),
        migrations.AddField(
            model_name='speciespresence',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lepidoptera.Species'),
        ),
        migrations.AddField(
            model_name='family',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lepidoptera.Status'),
        ),
    ]
