# Generated by Django 2.0.1 on 2018-01-17 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'families',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('order', models.IntegerField(help_text='In presence tables: order in which the provinces are displayed', unique=True)),
                ('historical', models.BooleanField(help_text="The province doesn't exists anymore")),
                ('recent', models.BooleanField(help_text='The province was created at province split')),
                ('polygon_reference', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesPresence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='speciespresence',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lepidoptera.TimePeriod'),
        ),
        migrations.AddField(
            model_name='speciespresence',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lepidoptera.Province'),
        ),
        migrations.AddField(
            model_name='speciespresence',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lepidoptera.Species'),
        ),
    ]
