# Generated by Django 2.0.1 on 2018-01-18 10:16

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0002_auto_20180117_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageFragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.SlugField(unique=True)),
                ('content_nl', markdownx.models.MarkdownxField(blank=True)),
                ('content_en', markdownx.models.MarkdownxField(blank=True)),
                ('content_fr', markdownx.models.MarkdownxField(blank=True)),
                ('content_ge', markdownx.models.MarkdownxField(blank=True)),
            ],
        ),
    ]
