# Generated by Django 2.0.1 on 2018-02-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0002_auto_20180214_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
