# Generated by Django 2.0.2 on 2018-02-20 13:27

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0003_auto_20180214_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='text',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AlterField(
            model_name='genus',
            name='synonym_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='lepidoptera.Genus'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='text',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='synonym_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='lepidoptera.Species'),
        ),
        migrations.AlterField(
            model_name='species',
            name='text',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AlterField(
            model_name='subfamily',
            name='text',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AlterField(
            model_name='subgenus',
            name='text',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AlterField(
            model_name='tribus',
            name='text',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
