# Generated by Django 2.0.1 on 2018-01-18 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0003_pagefragment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagefragment',
            old_name='content_ge',
            new_name='content_de',
        ),
    ]
