# Generated by Django 2.0.2 on 2018-02-28 09:17

import django.core.validators
from django.db import migrations, models
import lepidoptera.models


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0003_auto_20180228_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='code',
            field=models.CharField(max_length=50, unique=True, validators=[lepidoptera.models.validate_only_numbers_and_uppercase, django.core.validators.MinLengthValidator(4)]),
        ),
    ]
