# Generated by Django 2.0.1 on 2018-02-06 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0004_auto_20180202_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbatim_genus_id', models.IntegerField(help_text='From the Access database', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('vernacular_name', models.CharField(blank=True, max_length=255)),
                ('vernacular_name_de', models.CharField(blank=True, max_length=255, null=True)),
                ('vernacular_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('vernacular_name_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('vernacular_name_nl', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True)),
                ('display_order', models.IntegerField(unique=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lepidoptera.Status')),
                ('tribus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lepidoptera.Tribus')),
            ],
            options={
                'verbose_name_plural': 'genera',
            },
        ),
    ]
