# Generated by Django 2.0.1 on 2018-02-13 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0006_genus_synonym_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='genus',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lepidoptera.Family'),
        ),
        migrations.AddField(
            model_name='genus',
            name='subfamily',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lepidoptera.Subfamily'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='tribus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lepidoptera.Tribus'),
        ),
    ]
