stages:
    - deploy

saltstack_deploy:
    stage: deploy
    script:
        - sudo /usr/local/bin/salt-call --retcode-passthrough --output-diff --force-color --state-output=changes state.apply webapps.lepidoptera
    tags:
        - python
        - deploy
