stages:
    - deploy

saltstack_deploy:
    stage: deploy
    script:
        - sudo /usr/local/bin/salt-call --retcode-passthrough --force-color state.apply webapps.lepidoptera
    tags:
        - python
        - deploy
