# Generated by Django 2.0.3 on 2018-03-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0002_auto_20180322_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='genus',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hostplantfamily',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hostplantgenus',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hostplantspecies',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='species',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subfamily',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subgenus',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tribus',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
