# Generated by Django 2.0.3 on 2018-05-02 08:34

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0002_auto_20180502_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='imago_section_text',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
