# Generated by Django 2.0.8 on 2018-08-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['display_order'], 'verbose_name_plural': 'families'},
        ),
        migrations.AlterModelOptions(
            name='genus',
            options={'ordering': ['display_order'], 'verbose_name_plural': 'genera'},
        ),
        migrations.AlterModelOptions(
            name='hostplantspecies',
            options={'ordering': ['genus__name', 'name'], 'verbose_name_plural': 'Host plant species'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['display_order'], 'verbose_name_plural': 'species'},
        ),
        migrations.AlterModelOptions(
            name='subfamily',
            options={'ordering': ['display_order'], 'verbose_name_plural': 'subfamilies'},
        ),
        migrations.AlterModelOptions(
            name='subgenus',
            options={'ordering': ['display_order'], 'verbose_name_plural': 'subgenera'},
        ),
        migrations.AlterModelOptions(
            name='substrate',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tribus',
            options={'ordering': ['display_order'], 'verbose_name_plural': 'tribus'},
        ),
        migrations.AddField(
            model_name='speciespicture',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speciespicture',
            name='locality',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
