# Generated by Django 2.0.3 on 2018-04-12 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0002_auto_20180411_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='first_mention_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='species',
            name='first_mention_page',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='species',
            name='first_mention_publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lepidoptera.Publication'),
        ),
    ]
