# Generated by Django 2.0.2 on 2018-03-09 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0003_auto_20180309_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='plant_genus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lepidoptera.HostPlantGenus'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='plant_species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lepidoptera.HostPlantSpecies'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='substrate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lepidoptera.Substrate'),
        ),
    ]
