# Generated by Django 2.0.3 on 2018-05-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0003_species_imago_section_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('verbatim_photographer_id', models.IntegerField(blank=True, help_text='From the Access database', null=True, unique=True)),
            ],
        ),
    ]
