# Generated by Django 2.1 on 2018-09-06 08:45

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0004_auto_20180808_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciespicture',
            name='comment',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
