# Generated by Django 2.0.2 on 2018-03-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0004_auto_20180309_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostplantfamily',
            name='vernacular_name_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hostplantfamily',
            name='vernacular_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hostplantfamily',
            name='vernacular_name_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hostplantfamily',
            name='vernacular_name_nl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hostplantgenus',
            name='vernacular_name_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hostplantgenus',
            name='vernacular_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hostplantgenus',
            name='vernacular_name_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hostplantgenus',
            name='vernacular_name_nl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hostplantspecies',
            name='vernacular_name_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hostplantspecies',
            name='vernacular_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hostplantspecies',
            name='vernacular_name_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hostplantspecies',
            name='vernacular_name_nl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
