# Generated by Django 2.0.3 on 2018-03-29 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0004_auto_20180328_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbatim_id', models.IntegerField(blank=True, help_text='From the Access database', null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbatim_id', models.IntegerField(blank=True, help_text='From the Access database', null=True, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('year', models.CharField(max_length=10)),
                ('volume', models.CharField(max_length=10)),
                ('issue', models.CharField(blank=True, max_length=10)),
                ('page_numbers', models.CharField(blank=True, max_length=50)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lepidoptera.Journal')),
            ],
        ),
    ]
