# Generated by Django 2.0.3 on 2018-04-17 09:16

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0004_auto_20180413_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='egg_section_text',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
