# Generated by Django 2.0.5 on 2018-06-14 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0005_auto_20180502_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genus',
            name='direct_species_count',
        ),
        migrations.RemoveField(
            model_name='subgenus',
            name='species_count',
        ),
    ]
