# Generated by Django 2.0.3 on 2018-03-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0005_journal_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='page_numbers',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
