# Generated by Django 2.0.3 on 2018-04-17 11:51

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0005_species_egg_section_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='bag_section_text',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AddField(
            model_name='species',
            name='bionomics_section_text',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AddField(
            model_name='species',
            name='case_section_text',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AddField(
            model_name='species',
            name='cocoon_section_text',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AddField(
            model_name='species',
            name='habitat_section_text',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AddField(
            model_name='species',
            name='mine_section_text',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
