# Generated by Django 2.1 on 2018-09-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0005_speciespicture_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostplantspecies',
            name='genus_name',
            field=models.CharField(default='', editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
