# Generated by Django 2.0.3 on 2018-03-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0006_auto_20180329_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='issue',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='publication',
            name='volume',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.CharField(max_length=20),
        ),
    ]
