# Generated by Django 2.0.6 on 2018-07-10 13:51

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0006_auto_20180614_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='hostplants_section_text',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
