# Generated by Django 2.1 on 2018-09-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0006_hostplantspecies_genus_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostplantspecies',
            name='genus_name',
        ),
    ]
