# Generated by Django 2.0.6 on 2018-07-10 13:56

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0007_species_hostplants_section_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='flightperiod_section_text',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
