# Generated by Django 2.1 on 2018-09-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0009_auto_20180907_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostplantspecies',
            options={'ordering': ['genus_name', 'name'], 'verbose_name_plural': 'Host plant species'},
        ),
        migrations.AddField(
            model_name='family',
            name='species_counter',
            field=models.IntegerField(default=0),
        ),
    ]
