# Generated by Django 2.1 on 2018-09-14 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0010_auto_20180907_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='status',
        ),
        migrations.RemoveField(
            model_name='genus',
            name='status',
        ),
        migrations.RemoveField(
            model_name='species',
            name='status',
        ),
        migrations.RemoveField(
            model_name='subfamily',
            name='status',
        ),
        migrations.RemoveField(
            model_name='subgenus',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tribus',
            name='status',
        ),
    ]
