# Generated by Django 2.1 on 2018-09-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0011_auto_20180914_1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
