# Generated by Django 2.1 on 2018-09-25 12:54

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0012_delete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='establishment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='establishment_means',
            field=models.CharField(choices=[('NATIVE', 'Native'), ('INVASIVE', 'Invasive'), ('NATURALISED', 'Naturalised'), ('MIGRANT', 'Migrant')], default='NATIVE', max_length=25),
        ),
        migrations.AddField(
            model_name='species',
            name='establishment_remarks',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
