# Generated by Django 2.1 on 2018-10-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0013_auto_20180925_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'default_manager_name': 'objects', 'ordering': ['display_order'], 'verbose_name_plural': 'species'},
        ),
        migrations.AddField(
            model_name='genus',
            name='family_name',
            field=models.CharField(default='', editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='species',
            name='establishment_date',
            field=models.DateField(blank=True, help_text="The 'day' part will be ignored.", null=True),
        ),
    ]
