# Generated by Django 2.0.13 on 2019-03-14 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0016_create_gbif_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['author', 'year']},
        ),
    ]
