# Generated by Django 2.0.13 on 2019-04-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0017_auto_20190314_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='binomial_name',
            field=models.CharField(default='', editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
