# Generated by Django 2.0.13 on 2019-04-23 08:51

from django.db import migrations


def noop(apps, schema_editor):
    pass


def first_populate_cached_binomial(apps, schema_editor):
    # The Genus model was recently added a new binomial_name denormalized field. We
    # should make sure it's initially populated
    Species = apps.get_model('lepidoptera', 'Species')

    for s in Species.objects.all():
        s.binomial_name = '{genus} {specific_epithet}'.format(genus=s.genus_name, specific_epithet=s.name)
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0018_species_binomial_name'),
    ]

    operations = [
        migrations.RunPython(first_populate_cached_binomial, noop),
    ]
