# Generated by Django 2.0.13 on 2019-08-23 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0019_first_populate_cached_binomial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantGenusObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('plant_genus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lepidoptera.HostPlantGenus')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lepidoptera.Species')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlantSpeciesObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('plant_species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lepidoptera.HostPlantSpecies')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lepidoptera.Species')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubstrateObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lepidoptera.Species')),
                ('substrate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lepidoptera.Substrate')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
