# Generated by Django 2.0.13 on 2019-08-23 11:20

from django.db import migrations


def noop(apps, schema_editor):
    pass


def migrate_observation_data(apps, schema_editor):
    Observation = apps.get_model('lepidoptera', 'Observation')

    PlantSpeciesObservation = apps.get_model('lepidoptera', 'PlantSpeciesObservation')
    PlantGenusObservation = apps.get_model('lepidoptera', 'PlantGenusObservation')
    SubstrateObservation = apps.get_model('lepidoptera', 'SubstrateObservation')

    for obs in Observation.objects.all():
        if obs.plant_species:
            initial_order = PlantSpeciesObservation.objects.filter(species=obs.species).count()
            PlantSpeciesObservation.objects.create(species=obs.species, plant_species=obs.plant_species, order=initial_order)
        elif obs.plant_genus:
            initial_order = PlantGenusObservation.objects.filter(species=obs.species).count()
            PlantGenusObservation.objects.create(species=obs.species, plant_genus=obs.plant_genus, order=initial_order)
        else:
            initial_order = SubstrateObservation.objects.filter(species=obs.species).count()
            SubstrateObservation.objects.create(species=obs.species, substrate=obs.substrate, order=initial_order)


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0020_plantgenusobservation_plantspeciesobservation_substrateobservation'),
    ]

    operations = [
        migrations.RunPython(migrate_observation_data, noop),
    ]
