# Generated by Django 2.0.13 on 2019-08-30 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0022_auto_20190823_1509'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publication',
            unique_together={('author', 'year')},
        ),
    ]
