# Generated by Django 2.0.13 on 2019-08-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0023_auto_20190830_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='markdown_reference',
            field=models.CharField(default='', editable=False, max_length=276),
            preserve_default=False,
        ),
    ]
