# Generated by Django 2.0.13 on 2019-08-30 12:17
from django.db import migrations


def noop(apps, schema_editor):
    pass


def make_reference_populated(apps, schema_editor):
    Publication = apps.get_model('lepidoptera', 'Publication')

    for p in Publication.objects.all():
        # We need some disgusting hack to force the update of the denormalized field
        p.author = p.author + ' '
        p.save()
        p.author = p.author[:-1]
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0024_publication_markdown_reference'),
    ]

    operations = [
        migrations.RunPython(make_reference_populated, noop),
    ]

