# Generated by Django 2.0.13 on 2019-09-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0025_initial_value_markdown_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantgenusobservation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='plantspeciesobservation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='substrateobservation',
            options={},
        ),
        migrations.RemoveField(
            model_name='plantgenusobservation',
            name='order',
        ),
        migrations.RemoveField(
            model_name='plantspeciesobservation',
            name='order',
        ),
        migrations.RemoveField(
            model_name='substrateobservation',
            name='order',
        ),
    ]
