# Generated by Django 2.0.13 on 2019-09-13 09:19

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0026_auto_20190913_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantspeciesobservation',
            options={'ordering': ['the_order']},
        ),
        migrations.AddField(
            model_name='plantspeciesobservation',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='plantspeciesobservation',
            name='species',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lepidoptera.Species'),
        ),
    ]
