# Generated by Django 2.0.13 on 2019-09-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0028_auto_20190913_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantgenusobservation',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='plantspeciesobservation',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='substrateobservation',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
