# Generated by Django 2.0.13 on 2019-09-13 13:27

from django.db import migrations


def noop(apps, schema_editor):
    pass


def make_reference_populated(apps, schema_editor):
    Publication = apps.get_model('lepidoptera', 'Publication')

    for p in Publication.objects.all():
        p.markdown_reference = f"[[PUB: {p.author} {p.year}]]"
        p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0030_initial_order_observations'),
    ]

    operations = [
        migrations.RunPython(make_reference_populated, noop),
    ]
