# Generated by Django 2.0.13 on 2019-09-17 11:22

from django.db import migrations


def noop(apps, schema_editor):
    pass


def fix_reference(apps, schema_editor):
    Publication = apps.get_model('lepidoptera', 'Publication')

    for p in Publication.objects.all():
        p.markdown_reference = f"[[PUB:{p.author} {p.year}]]"
        p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('lepidoptera', '0031_initial_values_pub_ref'),
    ]

    operations = [
        migrations.RunPython(fix_reference, noop),
    ]
